version: "3"

services:
  web:
    container_name: innotter
    build: .
    command: sh ./entrypoint.sh
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    env_file:
      - ./.env
    depends_on:
      - db
      - rabbitmq
    restart: on-failure

  microservice:
    container_name: fastapi
    build: ./microservices/app
    ports:
      - "8001:8001"
    env_file:
      - ./.env

  db:
    container_name: database
    image: postgres:12.0-alpine
    volumes:
      - ./data/db:/var/lib/postgresql/data
    env_file:
      - ./.env

  rabbitmq:
    container_name: rabbitmq
    image: rabbitmq:3-management
    env_file:
      - ./.env
    ports:
      - 5672:5672
      - 15672:15672
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:15672"]
      interval: 30s
      timeout: 10s
      retries: 5

  celery:
    restart: always
    container_name: celery
    build: .
    command: sh ./entrypoint_celery.sh
    env_file:
      - ./.env
    volumes:
      - .:/app
    ports:
      - "5555:5555"
    depends_on:
      - rabbitmq

volumes:
  innotter_pg_data:
