version: "3.10"

services:
  web:
    container_name: innotter
    build: .
    command: python /app/innotter/manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    env_file:
      - ./.env
    depends_on:
      - db

  db:
    container_name: database
    image: postgres
    restart: always
    volumes:
      - ./data/db:/var/lib/postgresql/data
#    env_file:
#      - ./.env
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres_dev

volumes:
  innotter_postgres_data: