version: "3.10"

services:
  web:
    container_name: innotter
    build: .
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    env_file:
      - ./.env
    depends_on:
      - db

  db:
    container_name: database
    image: postgres:12.0-alpine
    volumes:
      - ./data/db:/var/lib/postgresql/data
    env_file:
      - ./.env

volumes:
  innotter_pg_data:
