# Generated by Django 4.0.4 on 2022-06-21 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_remove_user_image_s3_path_user_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='image',
        ),
        migrations.AddField(
            model_name='user',
            name='image_s3_path',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
